name: build sentry_streams_k8s

on:
  pull_request:
  push:
    branches:
      - main
      - release-sentry-streams-k8s/**

jobs:
  build:
    permissions: read-all
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.11
      - name: Make environment
        run: |
          make install-dev
      - name: Build wheel
        run: |
          cd sentry_streams_k8s
          uv pip install --system build
          python -m build --wheel
      - name: Upload wheels
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ${{ github.sha }}
          path: ./sentry_streams_k8s/dist
